### ISSUE TITLE
Query in Sparql.getQuerylabel

### ISSUE THREAD

**Issue by blanser** [ag-sc/matoll#78]
It seems that UNION is not leftbound; just tried out the following query at http://dbpedia.org/sparql...

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?y ?subj ?obj ?x WHERE {
    ?y <http://dbpedia.org/ontology/product> ?x. 
    {?y rdfs:label ?subj. FILTER (lang(?subj) = 'ja')} UNION 
    {?y rdfs:label ?subj. FILTER (lang(?subj) = 'en')}
    {?x rdfs:label ?obj. FILTER (lang(?obj) = 'ja')} UNION 
    {?x rdfs:label ?obj. FILTER (lang(?obj) = 'en')} 
} ORDER BY ?y ?x
```

...and when there were both a Japanese and an English label, it returned rows for both. I think this is not what is wanted here (or is it?).

**Comment by swalter2** [comment]
True, but we are going away from extracting the data from the endpoint, but doing it offline and from the original dbpedia data files, to get more combination of entity pairs - see comment to #98
